### ISSUE TITLE
AMBARISH's SOP-gatk-SARS-CoV-2

### ISSUE THREAD

**Issue by mr-c** [common-workflow-lab/2020-covid-19-bh#5]
https://github.com/common-workflow-lab/2020-covid-19-bh/blob/master/SOP-gatk-SARS-CoV-2.md

- [x] needs a GATK4 version, GATK3 is not Free nor Open Source so we can't use it

**Comment by ambarishK** [comment]
I have updated the pipeline/workflow/protocol. Sir, check for the updates. 
https://github.com/common-workflow-lab/2020-covid-19-bh/blob/master/SOP-GATK-SARS-CoV-2.md
